### ISSUE TITLE
fix the issue with the homepage displaying 9,000+ instead of the actual number

### ISSUE THREAD

**Issue by bharnav** [wwsalmon/stem4free#13]

**Comment by wwsalmon** [comment]
Caused by modification in spreadsheet:

![image](https://user-images.githubusercontent.com/25697428/84958146-b84a9780-b0ca-11ea-99e8-c49c719a3fe1.png)

Fixed the formatting and made the warning stronger/more specific:

![image](https://user-images.githubusercontent.com/25697428/84958160-c13b6900-b0ca-11ea-8447-d48015c4fc01.png)
